CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE SEQ_INVESTIMENTO START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE SEQ_OBJETIVO START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE SEQ_CATEGORIA START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE SEQ_RECEITA START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE SEQ_GASTO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE TABLE TGF_USUARIO(
    cod_usuario     NUMBER(10)          NOT NULL,
    usu_nome        VARCHAR2(32)        NOT NULL,
    usu_sobrenome   VARCHAR2(64)        NOT NULL,
    usu_email       VARCHAR2(60)        NOT NULL,
    usu_senha       VARCHAR2(16)        NOT NULL,
    usu_pais        VARCHAR2(64),
    dt_nascimento   DATE,
    CONSTRAINT PK_TGF_USUARIO PRIMARY KEY (cod_usuario)
);

CREATE TABLE TGF_INVESTIMENTO(
    cod_investimento    NUMBER (10)     NOT NULL,
    cod_usuario         NUMBER(10)      NOT NULL,
    des_investimento    VARCHAR2(32)    NOT NULL,
    val_investimento    NUMBER (10)     NOT NULL,
    nom_instituicao     VARCHAR2 (25),
    nom_tipo            VARCHAR2(32),
    dt_inicio           DATE            NOT NULL,
    dt_conclusao        DATE,
    CONSTRAINT PK_TGF_INVESTIMENTO PRIMARY KEY (cod_investimento)
);

CREATE TABLE TGF_OBJETIVO(
    cod_objetivo        NUMBER (10)     NOT NULL,
    cod_usuario         NUMBER(10)      NOT NULL,
    des_objetivo        VARCHAR2(32)    NOT NULL,
    val_objetivo        NUMBER (10)     NOT NULL,
    dt_inicio           DATE            NOT NULL,
    dt_conclusao        DATE,
    CONSTRAINT PK_TGF_OBJETIVO PRIMARY KEY (cod_objetivo)
);

CREATE TABLE TGF_CATEGORIA(
    cod_categoria       NUMBER(10)      NOT NULL,
    nom_categoria       VARCHAR2(32)    NOT NULL,
    des_categoria       VARCHAR2(64)    NULL,
    CONSTRAINT PK_TGF_CATEGORIA PRIMARY KEY(cod_categoria)
);

CREATE TABLE TGF_RECEITA(
    cod_receita         NUMBER (10)     NOT NULL,
    cod_usuario         NUMBER(10)      NOT NULL,
    des_receita         VARCHAR2(32)    NOT NULL,
    val_receita         NUMBER (10)     NOT NULL,
    dt_entrada          DATE            NOT NULL,
    CONSTRAINT PK_TGF_RECEITA PRIMARY KEY (cod_receita)
);

CREATE TABLE TGF_GASTO(
    cod_gasto       NUMBER (10)     NOT NULL,
    cod_usuario     NUMBER(10)      NOT NULL,
    des_gasto       VARCHAR2(32)    NOT NULL,
    val_gasto       NUMBER (10)     NOT NULL,
    dt_saida        DATE            NOT NULL,
    CONSTRAINT PK_TGF_GASTO PRIMARY KEY (cod_gasto)
);

ALTER TABLE TGF_GASTO
ADD cod_categoria NUMBER(10);

ALTER TABLE TGF_RECEITA
ADD cod_categoria NUMBER(10);

ALTER TABLE TGF_USUARIO
ADD CONSTRAINT UN_TGF_USUARIO_EMAIL UNIQUE (usu_email)

ALTER TABLE TGF_USUARIO
MODIFY (cod_usuario DEFAULT SEQ_USUARIO.NEXTVAL)

ALTER TABLE TGF_INVESTIMENTO
ADD CONSTRAINT UN_TGF_INVESTIMENTO_DESC UNIQUE (des_investimento)

ALTER TABLE TGF_INVESTIMENTO
ADD CONSTRAINT CK_TGF_INVESTIMENTO_VAL CHECK (val_investimento > 0)

ALTER TABLE TGF_INVESTIMENTO
ADD CONSTRAINT FK_COD_USUARIO_TGF_INVESTIMENTO FOREIGN KEY (cod_usuario) REFERENCES TGF_USUARIO (cod_usuario)

ALTER TABLE TGF_INVESTIMENTO
MODIFY (cod_investimento DEFAULT SEQ_INVESTIMENTO.NEXTVAL)

ALTER TABLE TGF_OBJETIVO
ADD CONSTRAINT FK_COD_USUARIO_TGF_OBJETIVO FOREIGN KEY (cod_usuario) REFERENCES TGF_USUARIO(cod_usuario)

ALTER TABLE TGF_OBJETIVO
ADD CONSTRAINT UN_TGF_OBJETIVO_DESC UNIQUE (des_objetivo)
    
ALTER TABLE TGF_OBJETIVO
ADD CONSTRAINT CK_TGF_OBJETIVO_VAL CHECK (val_objetivo > 0)

ALTER TABLE TGF_OBJETIVO
MODIFY (cod_objetivo DEFAULT SEQ_OBJETIVO.NEXTVAL)

ALTER TABLE TGF_CATEGORIA
ADD CONSTRAINT UN_TGF_CATEGORIA_NOME UNIQUE (nom_categoria)

ALTER TABLE TGF_CATEGORIA
MODIFY (cod_categoria DEFAULT SEQ_CATEGORIA.NEXTVAL)

ALTER TABLE TGF_RECEITA
ADD CONSTRAINT FK_COD_USUARIO_TGF_RECEITA FOREIGN KEY (cod_usuario) REFERENCES TGF_USUARIO(cod_usuario)

ALTER TABLE TGF_RECEITA
ADD CONSTRAINT CK_TGF_RECEITA_VAL CHECK (val_receita > 0)

ALTER TABLE TGF_RECEITA
ADD CONSTRAINT FK_COD_CATEGORIA_TGF_RECEITA FOREIGN KEY (cod_categoria) REFERENCES TGF_CATEGORIA(cod_categoria)

ALTER TABLE TGF_RECEITA
MODIFY (cod_receita DEFAULT SEQ_RECEITA.NEXTVAL)

ALTER TABLE TGF_GASTO
ADD CONSTRAINT FK_COD_USUARIO_TGF_GASTO FOREIGN KEY (cod_gasto) REFERENCES TGF_USUARIO(cod_usuario)

ALTER TABLE TGF_GASTO
ADD CONSTRAINT CK_TGF_GASTO_VAL CHECK (val_gasto > 0)

ALTER TABLE TGF_GASTO
ADD CONSTRAINT FK_TGF_GASTO_USUARIO FOREIGN KEY (cod_usuario) REFERENCES TGF_USUARIO (cod_usuario)

ALTER TABLE TGF_GASTO
ADD CONSTRAINT FK_TGF_GASTO_CATEGORIA FOREIGN KEY (cod_categoria) REFERENCES TGF_CATEGORIA (cod_categoria)

ALTER TABLE TGF_GASTO
MODIFY (cod_gasto DEFAULT SEQ_GASTO.NEXTVAL)

